name: Label issues by title

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  label_by_title:
    runs-on: ubuntu-latest
    steps:
      - name: Apply label based on issue title
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.issue.title.toLowerCase();
            console.log(`Processing issue #${context.payload.issue.number}: "${context.payload.issue.title}"`);
            
            const labelsToAdd = [];

            if (title.startsWith('feature/')) {
              labelsToAdd.push('feature');
            } else if (title.startsWith('bug/')) {
              labelsToAdd.push('bug');
            } else if (title.startsWith('enhancement/')) {
              labelsToAdd.push('enhancement');
            } else if (title.startsWith('docs/')) {
              labelsToAdd.push('documentation');
            } else if (title.startsWith('test/')) {
              labelsToAdd.push('testing');
            } else if (title.startsWith('chore/')) {
              labelsToAdd.push('chore');
            } else if (title.startsWith('refactor/')) {
              labelsToAdd.push('refactor');
            } else if (title.startsWith('security/')) {
              labelsToAdd.push('security');
            } else {
              // Optional: Add a default label if no match
              labelsToAdd.push('needs-triage');
            }

            if (labelsToAdd.length > 0) {
              try {
                console.log(`Adding labels: ${labelsToAdd.join(', ')}`);
                await github.rest.issues.addLabels({
                  issue_number: context.payload.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: labelsToAdd
                });
              } catch (error) {
                console.error(`Error adding labels: ${error.message}`);
                core.setFailed(`Failed to add labels: ${error.message}`);
              }
            }
