name: Label issues by title

on:
  issues:
    types: [opened, edited]

jobs:
  label_by_title:
    runs-on: ubuntu-latest
    steps:
      - name: Apply label based on issue title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title.toLowerCase();

            const labelsToAdd = [];

            if (title.startsWith('feature/')) {
              labelsToAdd.push('feature');
            } else if (title.startsWith('bug/')) {
              labelsToAdd.push('bug');
            } else if (title.startsWith('enhancement/')) {
              labelsToAdd.push('enhancement');
            }

            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                issue_number: context.payload.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labelsToAdd
              });
            }
